<a href="https://colab.research.google.com/github/Hemant10HM/ANNDL-LAB_24mcs004/blob/main/ANN_LAB_4_MLP_Optimizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Optimizers effect on Classification Model


In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.datasets import make_regression
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange, tqdm

#TensorFlow and Keras Libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import torch
from torchvision import transforms
from tensorflow.keras.utils import to_categorical
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os

# Hiding the warnings
import warnings
warnings.filterwarnings('ignore')

# Extra Libraries
import copy
import random
import time


In [2]:
# Define dataset path
dataset_path = "/content/drive/MyDrive/data/WineQT.csv"
df = pd.read_csv(dataset_path)

In [3]:
df.drop('Id', axis=1, inplace=True)

In [5]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5


In [6]:
# Craeting binary classification target
df['Good'] = df['quality'].apply(lambda x: 1 if x >= 7 else 0)

In [7]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0


In [8]:
X = df.drop(['quality', 'Good'], axis=1)

In [9]:
# Scale features
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)


In [10]:
# Round scaled features
X_scaled = X_scaled.round(2)

In [11]:

df.head()


,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0


In [12]:
X_bin = X_scaled.copy()
y_bin = df['Good']

In [13]:
# Train-Test Split :
X_train, X_test, y_train, y_test = train_test_split(X_bin,y_bin,test_size=0.33,random_state=42)
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (765, 11)
X_test shape :  (378, 11)
y_train shape :  (765,)
y_test shape :  (378,)


In [14]:

# Building MLP model for Binary Class Classification :
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(45,activation='relu',input_dim = 11))
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.Dense(15,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))


In [15]:
# 1. We are using adam optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=250)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - BinaryAccuracy: 0.8416 - loss: 0.6010
Epoch 2/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8493 - loss: 0.4453
Epoch 3/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8434 - loss: 0.4288
Epoch 4/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8659 - loss: 0.3760
Epoch 5/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8532 - loss: 0.3692  
Epoch 6/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8549 - loss: 0.3529 
Epoch 7/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8580 - loss: 0.3207 
Epoch 8/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8653 - loss: 0.3096 
Epoch 9/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8693 - loss: 0.2978 
Epoch 10/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8479 - loss: 0.3143 
Epoch 11/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8731 - los

In [16]:

start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8839 - loss: 0.4162  
Testing time: 0.26 seconds


In [17]:

y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)


12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step
(378, 1)
(378,)


In [18]:

# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)


Accuracy: 0.8862433862433863
Confusion Matrix:
 [[316  10]
 [ 33  19]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.97      0.94       326
           1       0.66      0.37      0.47        52

    accuracy                           0.89       378
   macro avg       0.78      0.67      0.70       378
weighted avg       0.87      0.89      0.87       378



In [19]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0


In [20]:
# 2. We are using rmsprop optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='rmsprop', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=250)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")


Epoch 1/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - BinaryAccuracy: 0.9242 - loss: 0.1751
Epoch 2/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9510 - loss: 0.1256 
Epoch 3/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9556 - loss: 0.1278 
Epoch 4/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9529 - loss: 0.1249 
Epoch 5/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9523 - loss: 0.1382 
Epoch 6/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9360 - loss: 0.1506 
Epoch 7/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9427 - loss: 0.1413 
Epoch 8/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9335 - loss: 0.1531 
Epoch 9/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9397 - loss: 0.1628 
Epoch 10/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9372 - loss: 0.1460 
Epoch 11/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9446 - l

In [21]:

start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8909 - loss: 0.7145  
Testing time: 0.27 seconds


In [22]:

y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
(378, 1)
(378,)


In [23]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.8915343915343915
Confusion Matrix:
 [[309  17]
 [ 24  28]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.95      0.94       326
           1       0.62      0.54      0.58        52

    accuracy                           0.89       378
   macro avg       0.78      0.74      0.76       378
weighted avg       0.89      0.89      0.89       378



In [24]:
# 3. We are using adagrad optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adagrad', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=250)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - BinaryAccuracy: 0.9678 - loss: 0.0736
Epoch 2/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9845 - loss: 0.0469
Epoch 3/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9833 - loss: 0.0563
Epoch 4/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9802 - loss: 0.0573
Epoch 5/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9788 - loss: 0.0559
Epoch 6/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9888 - loss: 0.0457
Epoch 7/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9851 - loss: 0.0477
Epoch 8/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9764 - loss: 0.0599
Epoch 9/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9874 - loss: 0.0461
Epoch 10/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9848 - loss: 0.0459
Epoch 11/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9830 - loss: 0.04

In [25]:

start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8872 - loss: 0.7351  
Testing time: 0.41 seconds


In [26]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
(378, 1)
(378,)


In [27]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.8888888888888888
Confusion Matrix:
 [[309  17]
 [ 25  27]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.95      0.94       326
           1       0.61      0.52      0.56        52

    accuracy                           0.89       378
   macro avg       0.77      0.73      0.75       378
weighted avg       0.88      0.89      0.88       378

