<a href="https://colab.research.google.com/github/Hemant10HM/ANNDL-LAB_24mcs004/blob/main/ANN_LAB_3_MLP_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.datasets import make_regression
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange, tqdm

#TensorFlow and Keras Libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import torch
from torchvision import transforms
from tensorflow.keras.utils import to_categorical
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os

# Hiding the warnings
import warnings
warnings.filterwarnings('ignore')

# Extra Libraries
import copy
import random
import time


In [2]:
# Define dataset path
dataset_path = "/content/drive/MyDrive/data/WineQT.csv"
df = pd.read_csv(dataset_path)

In [3]:
df.drop('Id', axis=1, inplace=True)

In [4]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5


In [5]:
# Craeting binary classification target
df['Good'] = df['quality'].apply(lambda x: 1 if x >= 7 else 0)

In [6]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0


In [7]:
X = df.drop(['quality', 'Good'], axis=1)

In [8]:
# Scale features
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)


In [9]:
# Round scaled features
X_scaled = X_scaled.round(2)

In [10]:

df.head()


,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0


In [12]:
X_bin = X_scaled.copy()
y_bin = df['Good']

In [13]:
# Train-Test Split :
X_train, X_test, y_train, y_test = train_test_split(X_bin,y_bin,test_size=0.33,random_state=42)
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (765, 11)
X_test shape :  (378, 11)
y_train shape :  (765,)
y_test shape :  (378,)


In [14]:

# Building MLP model for Binary Class Classification :
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(45,activation='relu',input_dim = 11))
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.Dense(15,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))


In [15]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['BinaryAccuracy'])
history = model.fit(X_train, y_train, epochs=250)

Epoch 1/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - BinaryAccuracy: 0.8634 - loss: 0.5888
Epoch 2/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8820 - loss: 0.4167  
Epoch 3/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8728 - loss: 0.3642 
Epoch 4/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8433 - loss: 0.3980 
Epoch 5/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8510 - loss: 0.3625
Epoch 6/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8387 - loss: 0.3690 
Epoch 7/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8447 - loss: 0.3313 
Epoch 8/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8343 - loss: 0.3540 
Epoch 9/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8766 - loss: 0.2882 
Epoch 10/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8607 - loss: 0.2760
Epoch 11/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8791 - lo

In [16]:

y_pred = model.predict(X_test)
y_pred.shape


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step


(378, 1)

In [17]:

y_bi_pred = (y_pred > 0.5).astype(int).flatten()
y_bi_pred.shape


(378,)

In [18]:

# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)


Accuracy: 0.8756613756613757
Confusion Matrix:
 [[308  18]
 [ 29  23]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.94      0.93       326
           1       0.56      0.44      0.49        52

    accuracy                           0.88       378
   macro avg       0.74      0.69      0.71       378
weighted avg       0.87      0.88      0.87       378



In [19]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0


In [20]:
#Multiclass now
X_multi = X_scaled.copy()
y_multi = df['quality']

In [30]:
y_shifted = y_multi - y_multi.min()
num_classes = len(np.unique(y_shifted))

# One-hot encode target labels
y_encoded = to_categorical(y_shifted, num_classes=num_classes)

In [42]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_multi, y_encoded, test_size=0.2, random_state=42, stratify=y_shifted)


In [43]:
print("X_Train Shape : ",X_train.shape)
print("X_Test Shape : ",X_test.shape)
print("y_train Shape : ",y_train.shape)
print("y_test Shape : ",y_test.shape)

X_Train Shape :  (914, 11)
X_Test Shape :  (229, 11)
y_train Shape :  (914, 6)
y_test Shape :  (229, 6)


In [44]:
# Build the MLP Model
model = tf.keras.Sequential()

# Model :
model.add(tf.keras.layers.Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

# Compile the Model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the Model
history = model.fit(X_train, y_train, epochs=250)



Epoch 1/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.4380 - loss: 1.6588
Epoch 2/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4453 - loss: 1.2097
Epoch 3/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5102 - loss: 1.1487
Epoch 4/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5354 - loss: 1.1238
Epoch 5/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5666 - loss: 1.0520
Epoch 6/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5692 - loss: 0.9884
Epoch 7/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5744 - loss: 1.0356
Epoch 8/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5699 - loss: 0.9965
Epoch 9/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6052 - loss: 0.9643
Epoch 10/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5915 - loss: 0.9585
Epoch 11/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6246 - loss: 0.9613
Epoch 12/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy:

In [45]:
pred_probs = model.predict(X_test)
pred_classes = np.argmax(pred_probs, axis=1)
original_preds = pred_classes + y_multi.min()  # Add the offset back


8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


In [46]:
# Also shift y_test back to original labels
y_test_original = np.argmax(y_test, axis=1) + y_multi.min()

# Accuracy
accuracy = accuracy_score(y_test_original, original_preds)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test_original, original_preds)

# Classification Report
class_report = classification_report(y_test_original, original_preds)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6506550218340611
Confusion Matrix:
 [[ 0  0  1  0  0  0]
 [ 0  1  3  3  0  0]
 [ 0  1 70 25  1  0]
 [ 0  1 20 63  8  0]
 [ 0  0  3  9 15  2]
 [ 0  0  0  1  2  0]]
Classification Report:
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.33      0.14      0.20         7
           5       0.72      0.72      0.72        97
           6       0.62      0.68      0.65        92
           7       0.58      0.52      0.55        29
           8       0.00      0.00      0.00         3

    accuracy                           0.65       229
   macro avg       0.38      0.34      0.35       229
weighted avg       0.64      0.65      0.64       229

